setwd("D:/work/coursera")
library(dplyr)
household <- read.table("household_power_consumption.txt", sep = ";", header = T, colClasses = "character")
household$Time <- strptime(paste(household$Date, household$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S")
household$Date <- as.Date(household$Date, format = "%d/%m/%Y")
household <- household[household$Date == "2007-02-01" | household$Date == "2007-02-02", ]
par(mfcol = c(1, 1), mar = c(5, 4, 4, 2)+0.1)
household$Sub_metering_1 <- as.numeric(household$Sub_metering_1)
household$Sub_metering_2 <- as.numeric(household$Sub_metering_2)
household$Sub_metering_3 <- as.numeric(household$Sub_metering_3)
png("plot3.png")
with(household, plot(Time, Sub_metering_1, type = "s", ylab = "Energy sub metering", xlab = ""))
with(household, lines(Time, Sub_metering_2, col = "red"))
with(household, lines(Time, Sub_metering_3, col = "blue"))
legend("topright", names(household)[7:9], lty = c(1, 1, 1), col = c("black", "red", "blue"))
dev.off()